export const adminUserTypes = {

  // Get all admin user list
  ADMIN_USER_LIST: "ADMIN_USER_LIST",
  GET_ADMIN_USER_REQUEST: 'GET_ADMIN_USER_REQUEST',
  GET_ADMIN_USER_SUCCESS: 'GET_ADMIN_USER_SUCCESS',
  GET_ADMIN_USER_FAILED: 'GET_ADMIN_USER_FAILED',
  UPDATE_ADMIN_USER_LIST: 'UPDATE_ADMIN_USER_LIST',
  // Get admin org detail
  GET_ADMIN_ORG_REQUEST: 'GET_ADMIN_ORG_REQUEST',
  GET_ADMIN_ORG_SUCCESS: 'GET_ADMIN_ORG_SUCCESS',
  GET_ADMIN_ORG_FAILED: 'GET_ADMIN_ORG_FAILED',
  // Get admin user detail
  GET_ADMIN_USER_DETAIL_REQUEST: 'GET_ADMIN_USER_DETAIL_REQUEST',
  GET_ADMIN_USER_DETAIL_SUCCESS: 'GET_ADMIN_USER_DETAIL_SUCCESS',
  GET_ADMIN_USER_DETAIL_FAILED: 'GET_ADMIN_USER_DETAIL_FAILED',
  UPDATE_ADMIN_USER_DETAIL: 'UPDATE_ADMIN_USER_DETAIL',
  
  // Update org user role
  CHANGE_ADMIN_USER_ROLE_REQUEST: 'CHANGE_ADMIN_USER_ROLE_REQUEST',
  CHANGE_ADMIN_USER_ROLE_SUCCESS: 'CHANGE_ADMIN_USER_ROLE_SUCCESS',
  CHANGE_ADMIN_USER_ROLE_FAILED: 'CHANGE_ADMIN_USER_ROLE_FAILED',
  CHANGE_ADMIN_USER_ROLE_RESET: 'CHANGE_ADMIN_USER_ROLE_RESET',
  
  // Remove user from org
  REMOVE_USER_FROM_ORG_REQUEST: 'REMOVE_USER_FROM_ORG_REQUEST',
  REMOVE_USER_FROM_ORG_SUCCESS: 'REMOVE_USER_FROM_ORG_SUCCESS',
  REMOVE_USER_FROM_ORG_FAILED: 'REMOVE_USER_FROM_ORG_FAILED',
  REMOVE_USER_FROM_ORG_RESET: 'REMOVE_USER_FROM_ORG_RESET',
  // Get all user list for make owner
  GET_OWNER_USER_REQUEST: 'GET_OWNER_USER_REQUEST',
  GET_OWNER_USER_SUCCESS: 'GET_OWNER_USER_SUCCESS',
  GET_OWNER_USER_FAILED: 'GET_OWNER_USER_FAILED',
  
  // Get all groups to invite user
  GET_ALL_ADMIN_GROUP_REQUEST: 'GET_ALL_ADMIN_GROUP_REQUEST',
  GET_ALL_ADMIN_GROUP_SUCCESS: 'GET_ALL_ADMIN_GROUP_SUCCESS',
  GET_ALL_ADMIN_GROUP_FAILED: 'GET_ALL_ADMIN_GROUP_FAILED',
  GET_ALL_ADMIN_GROUP_RESET: 'GET_ALL_ADMIN_GROUP_RESET',
  GET_ALL_ADMIN_GROUP_UPDATE: 'GET_ALL_ADMIN_GROUP_UPDATE',
  
  // Get current user session detsil
  GET_USER_SESSION_REQUEST: 'GET_USER_SESSION_REQUEST',
  GET_USER_SESSION_SUCCESS: 'GET_USER_SESSION_SUCCESS',
  GET_USER_SESSION_FAILED: 'GET_USER_SESSION_FAILED',
  GET_USER_SESSION_RESET: 'GET_USER_SESSION_RESET',
  GET_USER_SESSIONP_UPDATE: 'GET_USER_SESSIONP_UPDATE',
  
};
