export const adminEventTypes = {
  // Admin event list
  ADM_EVT_LIST_REQUEST: 'ADM_EVT_LIST_REQUEST_DETAILS',
  ADM_EVT_LIST_SUCCESS: 'ADM_EVT_LIST_SUCCESS_DETAILS',
  ADM_EVT_LIST_UPDATE: 'ADM_EVT_LIST_UPDATE_DETAILS',
  ADM_EVT_LIST_FAILED: 'ADM_EVT_LIST_FAILED_DETAILS',
  ADM_EVT_LIST_RESET: 'ADM_EVT_LIST_RESET',

  // Change visibility 
  EVT_CHANGE_VISIBILITY_REQUEST: 'EVT_CHANGE_VISIBILITY_REQUEST_DETAILS',
  EVT_CHANGE_VISIBILITY_SUCCESS: 'EVT_CHANGE_VISIBILITY_SUCCESS_DETAILS',
  EVT_CHANGE_VISIBILITY_FAILED: 'EVT_CHANGE_VISIBILITY_FAILED_DETAILS',

  // Remove user from event
  KICK_USER_FROM_EVENT_REQUEST: 'KICK_USER_FROM_EVENT_REQUEST_DETAILS',
  KICK_USER_FROM_EVENT_SUCCESS: 'KICK_USER_FROM_EVENT_SUCCESS_DETAILS',
  KICK_USER_FROM_EVENT_FAILED: 'KICK_USER_FROM_EVENT_FAILED_DETAILS',
  KICK_USER_FROM_EVENT_RESET: 'KICK_USER_FROM_EVENT_RESET_DETAILS',
};
