export const adminGroupTypes = {

  // Admin group list
  ADM_GRP_LIST_REQUEST: 'ADM_GRP_LIST_REQUEST_DETAILS',
  ADM_GRP_LIST_SUCCESS: 'ADM_GRP_LIST_SUCCESS_DETAILS',
  ADM_GRP_LIST_UPDATE: 'ADM_GRP_LIST_UPDATE_DETAILS',
  ADM_GRP_LIST_FAILED: 'ADM_GRP_LIST_FAILED_DETAILS',
  
  // Change visibility 
  CHANGE_VISIBILITY_REQUEST: 'CHANGE_VISIBILITY_REQUEST_DETAILS',
  CHANGE_VISIBILITY_SUCCESS: 'CHANGE_VISIBILITY_SUCCESS_DETAILS',
  CHANGE_VISIBILITY_FAILED: 'CHANGE_VISIBILITY_FAILED_DETAILS',

  // Assign new group owner
  ASSIGN_NEW_GROUP_OWNER_REQUEST: 'ASSIGN_NEW_GROUP_OWNER_REQUEST_DETAILS',
  ASSIGN_NEW_GROUP_OWNER_SUCCESS: 'ASSIGN_NEW_GROUP_OWNER_SUCCESS_DETAILS',
  ASSIGN_NEW_GROUP_OWNER_FAILED: 'ASSIGN_NEW_GROUP_OWNER_FAILED_DETAILS',

  // Invite group member list
  INVITE_TO_GROUP_MEMBER_LIST_REQUEST: 'INVITE_TO_GROUP_MEMBER_LIST_REQUEST_DETAILS',
  INVITE_TO_GROUP_MEMBER_LIST_SUCCESS: 'INVITE_TO_GROUP_MEMBER_LIST_SUCCESS_DETAILS',
  INVITE_TO_GROUP_MEMBER_LIST_UPDATE: 'INVITE_TO_GROUP_MEMBER_LIST_UPDATE_DETAILS',
  INVITE_TO_GROUP_MEMBER_LIST_FAILED: 'INVITE_TO_GROUP_MEMBER_LIST_FAILED_DETAILS',

  // Invite group member
  INVITE_GROUP_MEMBER_REQUEST: 'INVITE_GROUP_MEMBER_REQUEST_DETAILS',
  INVITE_GROUP_MEMBER_SUCCESS: 'INVITE_GROUP_MEMBER_SUCCESS_DETAILS',
  INVITE_GROUP_MEMBER_FAILED: 'INVITE_GROUP_MEMBER_FAILED_DETAILS',

  // Cancle invite group member
  CANCLE_INVITE_GROUP_MEMBER_REQUEST: 'CANCLE_INVITE_GROUP_MEMBER_REQUEST_DETAILS',
  CANCLE_INVITE_GROUP_MEMBER_SUCCESS: 'CANCLE_INVITE_GROUP_MEMBER_SUCCESS_DETAILS',
  CANCLE_INVITE_GROUP_MEMBER_FAILED: 'CANCLE_INVITE_GROUP_MEMBER_FAILED_DETAILS',
  
  // Delete admin group
  DELETE_ADM_GRP_REQUEST: 'DELETE_ADM_GRP_REQUEST_DETAILS',
  DELETE_ADM_GRP_SUCCESS: 'DELETE_ADM_GRP_SUCCESS_DETAILS',
  DELETE_ADM_GRP_FAILED: 'DELETE_ADM_GRP_FAILED_DETAILS',

  // Admin group details
  ADM_GRP_DETAILS_REQUEST: 'ADM_GRP_DETAILS_REQUEST_DETAILS',
  ADM_GRP_DETAILS_SUCCESS: 'ADM_GRP_DETAILS_SUCCESS_DETAILS',
  ADM_GRP_DETAILS_FAILED: 'ADM_GRP_DETAILS_FAILED_DETAILS',
  
  // Admin edit group details
  ADM_EDIT_GRP_DETAILS_REQUEST: 'ADM_EDIT_GRP_DETAILS_REQUEST_DETAILS',
  ADM_EDIT_GRP_DETAILS_SUCCESS: 'ADM_EDIT_GRP_DETAILS_SUCCESS_DETAILS',
  ADM_EDIT_GRP_DETAILS_FAILED: 'ADM_EDIT_GRP_DETAILS_FAILED_DETAILS',
  
  // Admin group member list
  GRP_DETAILS_MEMBER_LIST_REQUEST: 'GRP_DETAILS_MEMBER_LIST_REQUEST_DETAILS',
  GRP_DETAILS_MEMBER_LIST_SUCCESS: 'GRP_DETAILS_MEMBER_LIST_SUCCESS_DETAILS',
  GRP_DETAILS_MEMBER_LIST_UPDATE: 'GRP_DETAILS_MEMBER_LIST_UPDATE_DETAILS',
  GRP_DETAILS_MEMBER_LIST_FAILED: 'GRP_DETAILS_MEMBER_LIST_FAILED_DETAILS',
  GRP_DETAILS_MEMBER_LIST_RESET: 'GRP_DETAILS_MEMBER_LIST_RESET_DETAILS',

  // Change user role
  PROMOTE_USER_ROLE_REQUEST: 'PROMOTE_USER_ROLE_REQUEST_DETAILS',
  PROMOTE_USER_ROLE_SUCCESS: 'PROMOTE_USER_ROLE_SUCCESS_DETAILS',
  PROMOTE_USER_ROLE_FAILED: 'PROMOTE_USER_ROLE_FAILED_DETAILS',
  PROMOTE_USER_ROLE_RESET: 'PROMOTE_USER_ROLE_RESET',

  // Remove user from group
  KICK_USER_FROM_GROUP_REQUEST: 'KICK_USER_FROM_GROUP_REQUEST_DETAILS',
  KICK_USER_FROM_GROUP_SUCCESS: 'KICK_USER_FROM_GROUP_SUCCESS_DETAILS',
  KICK_USER_FROM_GROUP_FAILED: 'KICK_USER_FROM_GROUP_FAILED_DETAILS',
  KICK_USER_FROM_GROUP_RESET: 'KICK_USER_FROM_GROUP_RESET_DETAILS',

  // Group event list
  GROUP_EVENT_LIST_REQUEST: 'GROUP_EVENT_LIST_REQUEST_DETAILS',
  GROUP_EVENT_LIST_SUCCESS: 'GROUP_EVENT_LIST_SUCCESS_DETAILS',
  GROUP_EVENT_LIST_FAILED: 'GROUP_EVENT_LIST_FAILED_DETAILS',
  GROUP_EVENT_LIST_UPDATE: 'GROUP_EVENT_LIST_UPDATE_DETAILS',

  // Delete group event
  DELETE_GROUP_EVENT_REQUEST: 'DELETE_GROUP_EVENT_REQUEST_DETAILS',
  DELETE_GROUP_EVENT_SUCCESS: 'DELETE_GROUP_EVENT_SUCCESS_DETAILS',
  DELETE_GROUP_EVENT_FAILED: 'DELETE_GROUP_EVENT_FAILED_DETAILS',

  // Delete group event
  INVITE_GROUP_EVENT_REQUEST: 'INVITE_GROUP_EVENT_REQUEST_DETAILS',
  INVITE_GROUP_EVENT_SUCCESS: 'INVITE_GROUP_EVENT_SUCCESS_DETAILS',
  INVITE_GROUP_EVENT_FAILED: 'INVITE_GROUP_EVENT_FAILED_DETAILS',

  // Create an admin event
  CREATE_ADMIN_EVENT_REQUEST: 'EVENT_CREATE_ADMIN_EVENT_REQUEST',
  CREATE_ADMIN_EVENT_SUCCESS: 'EVENT_CREATE_ADMIN_EVENT_SUCCESS',
  CREATE_ADMIN_EVENT_FAILED: 'EVENT_CREATE_ADMIN_EVENT_FAILED',

  // Create an admin event
  EDIT_ADMIN_EVENT_REQUEST: 'EVENT_EDIT_ADMIN_EVENT_REQUEST',
  EDIT_ADMIN_EVENT_SUCCESS: 'EVENT_EDIT_ADMIN_EVENT_SUCCESS',
  EDIT_ADMIN_EVENT_FAILED: 'EVENT_EDIT_ADMIN_EVENT_FAILED',
  EDIT_ADMIN_EVENT_FLAG_UPDATE: 'EVENT_EDIT_ADMIN_EVENT_FLAG_UPDATE',

  // Create an admin group
  CREATE_ADMIN_GROUP_REQUEST: 'CREATE_ADMIN_GROUP_REQUEST_DETAILS',
  CREATE_ADMIN_GROUP_SUCCESS: 'CREATE_ADMIN_GROUP_SUCCESS_DETAILS',
  CREATE_ADMIN_GROUP_FAILED: 'CREATE_ADMIN_GROUP_FAILED_DETAILS',

  // Update an admin group
  UPDATE_ADMIN_GROUP_REQUEST: 'UPDATE_ADMIN_GROUP_REQUEST_DETAILS',
  UPDATE_ADMIN_GROUP_SUCCESS: 'UPDATE_ADMIN_GROUP_SUCCESS_DETAILS',
  UPDATE_ADMIN_GROUP_FAILED: 'UPDATE_ADMIN_GROUP_FAILED_DETAILS',

  RESET_SOME_GRP_STATE: 'RESET_SOME_GRP_STATE_DETAILS',

  RESET_ADM_GRP_STATE: 'RESET_ADM_GRP_STATE_DETAILS',
};
