export const discoverTypes = {

  // Get all discover details
  ALL_DISCOVER_REQUEST: 'ALL_DISCOVER_DETAILS_REQUEST',
  ALL_DISCOVER_SUCCESS: 'ALL_DISCOVER_DETAILS_SUCCESS',
  ALL_DISCOVER_FAILED: 'ALL_DISCOVER_DETAILS_FAILED',
  ALL_DISCOVER_UPDATE: 'ALL_DISCOVER_DETAILS_UPDATE',

  // Get default discover details
  DEFAULT_DISCOVER_REQUEST: 'DEFAULT_DISCOVER_DETAILS_REQUEST',
  DEFAULT_DISCOVER_SUCCESS: 'DEFAULT_DISCOVER_DETAILS_SUCCESS',
  DEFAULT_DISCOVER_FAILED: 'DEFAULT_DISCOVER_DETAILS_FAILED',

  // Get organization discover details
  ORG_DISCOVER_REQUEST: 'ORG_DISCOVER_DETAILS_REQUEST',
  ORG_DISCOVER_SUCCESS: 'ORG_DISCOVER_DETAILS_SUCCESS',
  ORG_DISCOVER_FAILED: 'ORG_DISCOVER_DETAILS_FAILED',

  // Get group discover details
  GRP_DISCOVER_REQUEST: 'GRP_DISCOVER_DETAILS_REQUEST',
  GRP_DISCOVER_SUCCESS: 'GRP_DISCOVER_DETAILS_SUCCESS',
  GRP_DISCOVER_FAILED: 'GRP_DISCOVER_DETAILS_FAILED',
  GRP_DISCOVER_UPDATE: 'GRP_DISCOVER_DETAILS_UPDATE',

  // Get event discover details
  EVT_DISCOVER_REQUEST: 'EVT_DISCOVER_DETAILS_REQUEST',
  EVT_DISCOVER_SUCCESS: 'EVT_DISCOVER_DETAILS_SUCCESS',
  EVT_DISCOVER_FAILED: 'EVT_DISCOVER_DETAILS_FAILED',
  EVT_DISCOVER_UPDATE: 'EVT_DISCOVER_DETAILS_UPDATE',

  // Get people discover details
  PPL_DISCOVER_REQUEST: 'PPL_DISCOVER_DETAILS_REQUEST',
  PPL_DISCOVER_SUCCESS: 'PPL_DISCOVER_DETAILS_SUCCESS',
  PPL_DISCOVER_FAILED: 'PPL_DISCOVER_DETAILS_FAILED',

};
