export const groupTypes = {

  // Get organization details
  CREATE_REQUEST: 'CREATE_GROUP_REQUEST',
  CREATE_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_FAILED: 'CREATE_GROUP_FAILED',

  // Get organization details
  UPDATE_REQUEST: 'UPDATE_GROUP_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_GROUP_SUCCESS',
  UPDATE_FAILED: 'UPDATE_GROUP_FAILED',

  // Get organization details
  SEARCH_MEMBER_REQUEST: 'SEARCH_ORGANIZATION_GROUP_MEMBERS_REQUEST',
  SEARCH_MEMBER_SUCCESS: 'SEARCH_ORGANIZATION_GROUP_MEMBERS_SUCCESS',
  SEARCH_MEMBER_FAILED: 'SEARCH_ORGANIZATION_GROUP_MEMBERS_FAILED',

  // Invite organization group member
  INVITE_MEMBER_REQUEST: 'INVITE_ORGANIZATION_GROUP_MEMBERS_REQUEST',
  INVITE_MEMBER_SUCCESS: 'INVITE_ORGANIZATION_GROUP_MEMBERS_SUCCESS',
  INVITE_MEMBER_FAILED: 'INVITE_ORGANIZATION_GROUP_MEMBERS_FAILED',

  // Invite member to group call
  INVITE_MEMBER_GROUP_CALL_REQUEST: 'INVITE_MEMBER_GROUP_CALL_REQUEST',
  INVITE_MEMBER_GROUP_CALL_SUCCESS: 'INVITE_MEMBER_GROUP_CALL_SUCCESS',
  INVITE_MEMBER_GROUP_CALL_FAILED: 'INVITE_MEMBER_GROUP_CALL_FAILED',

  // Cancel member invitation
  CANCEL_MEMBER_INVITATION_REQUEST: 'CANCEL_INVITATION_ORGANIZATION_GROUP_MEMBERS_REQUEST',
  CANCEL_MEMBER_INVITATION_SUCCESS: 'CANCEL_INVITATION_ORGANIZATION_GROUP_MEMBERS_SUCCESS',
  CANCEL_MEMBER_INVITATION_FAILED: 'CANCEL_INVITATION_ORGANIZATION_GROUP_MEMBERS_FAILED',

  // Create group event
  CREATE_EVENT_REQUEST: 'CREATE_GROUP_EVENT_REQUEST',
  CREATE_EVENT_SUCCESS: 'CREATE_GROUP_EVENT_SUCCESS',
  CREATE_EVENT_FAILED: 'CREATE_GROUP_EVENT_FAILED',

  // Join event
  JOIN_EVENT_REQUEST: 'JOIN_GROUP_EVENT_REQUEST',
  JOIN_EVENT_SUCCESS: 'JOIN_GROUP_EVENT_SUCCESS',
  JOIN_EVENT_FAILED: 'JOIN_GROUP_EVENT_FAILED',

  // Guest Join event
  GUEST_JOIN_EVENT_REQUEST: 'GUEST_JOIN_GROUP_EVENT_REQUEST',
  GUEST_JOIN_EVENT_SUCCESS: 'GUEST_JOIN_GROUP_EVENT_SUCCESS',
  GUEST_JOIN_EVENT_FAILED: 'GUEST_JOIN_GROUP_EVENT_FAILED',

  // Reset member invitation state
  RESET_MEMBER_INVITATION: 'RESET_INVITATION_ORGANIZATION_GROUP_MEMBERS',

  // Organization list
  ORG_GRP_LIST_REQUEST: 'ORG_GRP_LIST_REQUEST_DETAILS',
  ORG_GRP_LIST_SUCCESS: 'ORG_GRP_LIST_SUCCESS_DETAILS',
  ORG_GRP_LIST_UPDATE: 'ORG_GRP_LIST_UPDATE_DETAILS',
  ORG_GRP_LIST_FAILED: 'ORG_GRP_LIST_FAILED_DETAILS',

  // Get Group details
  GROUP_DETAILS_REQUEST: 'GROUP_DETAILS_REQUEST_DETAILS',
  GROUP_DETAILS_SUCCESS: 'GROUP_DETAILS_SUCCESS_DETAILS',
  GROUP_DETAILS_FAILED: 'GROUP_DETAILS_FAILED_DETAILS',

  // Get Group edit details
  GROUP_EDIT_DETAILS_REQUEST: 'GROUP_EDIT_DETAILS_REQUEST_DETAILS',
  GROUP_EDIT_DETAILS_SUCCESS: 'GROUP_EDIT_DETAILS_SUCCESS_DETAILS',
  GROUP_EDIT_DETAILS_FAILED: 'GROUP_EDIT_DETAILS_FAILED_DETAILS',

  // Get Group member
  GROUP_MEMBER_REQUEST: 'GROUP_MEMBER_REQUEST_DETAILS',
  GROUP_MEMBER_SUCCESS: 'GROUP_MEMBER_SUCCESS_DETAILS',
  GROUP_MEMBER_FAILED: 'GROUP_MEMBER_FAILED_DETAILS',

  // Join Group
  JOIN_GROUP_REQUEST: 'JOIN_GROUP_REQUEST_DETAILS',
  JOIN_GROUP_SUCCESS: 'JOIN_GROUP_SUCCESS_DETAILS',
  JOIN_GROUP_FAILED: 'JOIN_GROUP_FAILED_DETAILS',

  // Leave Group
  LEAVE_GROUP_REQUEST: 'LEAVE_GROUP_REQUEST_DETAILS',
  LEAVE_GROUP_SUCCESS: 'LEAVE_GROUP_SUCCESS_DETAILS',
  LEAVE_GROUP_FAILED: 'LEAVE_GROUP_FAILED_DETAILS',

  // Delete Group
  DELETE_GROUP_REQUEST: 'DELETE_GROUP_REQUEST_DETAILS',
  DELETE_GROUP_SUCCESS: 'DELETE_GROUP_SUCCESS_DETAILS',
  DELETE_GROUP_FAILED: 'DELETE_GROUP_FAILED_DETAILS',

  // Resume Group
  RESUME_GROUP_REQUEST: 'RESUME_GROUP_REQUEST_DETAILS',
  RESUME_GROUP_SUCCESS: 'RESUME_GROUP_SUCCESS_DETAILS',
  RESUME_GROUP_FAILED: 'RESUME_GROUP_FAILED_DETAILS',

  // Mute Group
  MUTE_GROUP_REQUEST: 'MUTE_GROUP_REQUEST_DETAILS',
  MUTE_GROUP_SUCCESS: 'MUTE_GROUP_SUCCESS_DETAILS',
  MUTE_GROUP_FAILED: 'MUTE_GROUP_FAILED_DETAILS',

  // Get organization list
  ORG_LIST_REQUEST: 'ORG_LIST_REQUEST_DETAILS',
  ORG_LIST_SUCCESS: 'ORG_LIST_SUCCESS_DETAILS',
  ORG_LIST_FAILED: 'ORG_LIST_FAILED_DETAILS',

  // Delete Group member
  DELETE_GROUP_MEMBER_REQUEST: 'DELETE_GROUP_MEMBER_REQUEST_DETAILS',
  DELETE_GROUP_MEMBER_SUCCESS: 'DELETE_GROUP_MEMBER_SUCCESS_DETAILS',
  DELETE_GROUP_MEMBER_FAILED: 'DELETE_GROUP_MEMBER_FAILED_DETAILS',

  // Make Owner
  MAKE_OWNER_REQUEST: 'MAKE_OWNER_REQUEST_DETAILS',
  MAKE_OWNER_SUCCESS: 'MAKE_OWNER_SUCCESS_DETAILS',
  MAKE_OWNER_FAILED: 'MAKE_OWNER_FAILED_DETAILS',

  // Make Owner
  CHANGE_USER_ROLE_REQUEST: 'CHANGE_USER_ROLE_REQUEST_DETAILS',
  CHANGE_USER_ROLE_SUCCESS: 'CHANGE_USER_ROLE_SUCCESS_DETAILS',
  CHANGE_USER_ROLE_FAILED: 'CHANGE_USER_ROLE_FAILED_DETAILS',

  RESET_GRP_STATE: 'RESET_GRP_STATE_DETAILS',
};
