export const notificationTypes = {

  // Notification list
  LIST_REQUEST: 'NOTIFICATION_LIST_REQUEST',
  LIST_SUCCESS: 'NOTIFICATION_LIST_SUCCESS',
  UPDATE_LIST: 'UPDATE_NOTIFICATION_LIST',
  LIST_FAILED: 'NOTIFICATION_LIST_FAILED',

  // Accept Reject notification invite
  ACCEPT_REJECT_REQUEST: 'ACCEPT_REJECT_INVITE_NOTIFICATION_REQUEST',
  ACCEPT_REJECT_SUCCESS: 'ACCEPT_REJECT_INVITE_NOTIFICATION_SUCCESS',
  ACCEPT_REJECT_FAILED: 'ACCEPT_REJECT_INVITE_NOTIFICATION_FAILED',

  // Notification notification invite
  DELETE_REQUEST: 'DELETE_NOTIFICATION_REQUEST',
  DELETE_SUCCESS: 'DELETE_NOTIFICATION_SUCCESS',
  DELETE_FAILED: 'DELETE_NOTIFICATION_FAILED',

  // Manage Notification read and unread
  READ_UNREAD_REQUEST: 'READ_UNREAD_NOTIFICATION_STATUS_REQUEST',
  READ_UNREAD_SUCCESS: 'READ_UNREAD_NOTIFICATION_STATUS_SUCCESS',
  READ_UNREAD_FAILED: 'READ_UNREAD_NOTIFICATION_STATUS_FAILED',

  // Get unread notifications count
  UNREAD_COUNT_REQUEST: 'UNREAD_COUNT_NOTIFICATION_REQUEST',
  UNREAD_COUNT_SUCCESS: 'UNREAD_COUNT_NOTIFICATION_SUCCESS',
  UNREAD_COUNT_FAILED: 'UNREAD_COUNT_NOTIFICATION_FAILED',

  RESET_STATE: 'RESET_NOTIFICATION_STATE',
};
