export const openTypes = {

  // Reset organization
  RESET_STORE: 'RESET_OPEN_STORE',

  // Check organization code details
  CHECK_ORG_CODE_REQUEST: 'CHECK_ORG_CODE_DETAILS_REQUEST',
  CHECK_ORG_CODE_SUCCESS: 'CHECK_ORG_CODE_DETAILS_SUCCESS',
  CHECK_ORG_CODE_FAILED: 'CHECK_ORG_CODE_DETAILS_FAILED',

  // Check organization code details
  SEAT_NOTIFY_REQUEST: 'SEAT_NOTIFY_DETAILS_REQUEST',
  SEAT_NOTIFY_SUCCESS: 'SEAT_NOTIFY_DETAILS_SUCCESS',
  SEAT_NOTIFY_FAILED: 'SEAT_NOTIFY_DETAILS_FAILED',
};
