export const organizationTypes = {

  // Get organization details
  BY_ID_REQUEST: 'ORGANIZATION_DETAILS_BY_ID_REQUEST',
  BY_ID_SUCCESS: 'ORGANIZATION_DETAILS_BY_ID_SUCCESS',
  BY_ID_FAILED: 'ORGANIZATION_DETAILS_BY_ID_FAILED',

  // Update organization details
  UPDATE_REQUEST: 'ORGANIZATION_DETAILS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'ORGANIZATION_DETAILS_UPDATE_SUCCESS',
  UPDATE_FAILED: 'ORGANIZATION_DETAILS_UPDATE_FAILED',

  // Get State List
  ORG_STATE_LIST_REQUEST: 'ORG_STATE_LIST_DETAILS_REQUEST',
  ORG_STATE_LIST_SUCCESS: 'ORG_STATE_LIST_DETAILS_SUCCESS',
  ORG_STATE_LIST_FAILED: 'ORG_STATE_LIST_DETAILS_FAILED',

  // Check organization
  CHECK_SUBSCRIPTION_REQUEST: 'CHECK_ORGANIZATION_SUBSCRIPTION_REQUEST',
  CHECK_SUBSCRIPTION_SUCCESS: 'CHECK_ORGANIZATION_SUBSCRIPTION_SUCCESS',
  CHECK_SUBSCRIPTION_FAILED: 'CHECK_ORGANIZATION_SUBSCRIPTION_FAILED',

  // Mange organization
  MANAGE_SUBSCRIPTION_REQUEST: 'MANAGE_ORGANIZATION_SUBSCRIPTION_REQUEST',
  MANAGE_SUBSCRIPTION_SUCCESS: 'MANAGE_ORGANIZATION_SUBSCRIPTION_SUCCESS',
  MANAGE_SUBSCRIPTION_FAILED: 'MANAGE_ORGANIZATION_SUBSCRIPTION_FAILED',

  // Get organization details
  SEARCH_MEMBER_REQUEST: 'SEARCH_ORGANIZATION_MEMBERS_REQUEST',
  SEARCH_MEMBER_SUCCESS: 'SEARCH_ORGANIZATION_MEMBERS_SUCCESS',
  SEARCH_MEMBER_FAILED: 'SEARCH_ORGANIZATION_MEMBERS_FAILED',

  // Invite organization group member
  INVITE_MEMBER_REQUEST: 'INVITE_ORGANIZATION_MEMBERS_REQUEST',
  INVITE_MEMBER_SUCCESS: 'INVITE_ORGANIZATION_MEMBERS_SUCCESS',
  INVITE_MEMBER_FAILED: 'INVITE_ORGANIZATION_MEMBERS_FAILED',

  // Cancel member invitation
  CANCEL_MEMBER_INVITATION_REQUEST: 'CANCEL_ORGANIZATION_MEMBERS_INVITATION_REQUEST',
  CANCEL_MEMBER_INVITATION_SUCCESS: 'CANCEL_ORGANIZATION_MEMBERS_INVITATION_SUCCESS',
  CANCEL_MEMBER_INVITATION_FAILED: 'CANCEL_ORGANIZATION_MEMBERS_INVITATION_FAILED',

  // Check organization notification  mute
  CHECK_NOTIFICATION_MUTE_REQUEST: 'CHECK_ORGANIZATION_NOTIFICATION_MUTE_REQUEST',
  CHECK_NOTIFICATION_MUTE_SUCCESS: 'CHECK_ORGANIZATION_NOTIFICATION_MUTE_SUCCESS',
  CHECK_NOTIFICATION_MUTE_FAILED: 'CHECK_ORGANIZATION_NOTIFICATION_MUTE_FAILED',

  // Mange organization notification  mute
  MANAGE_NOTIFICATION_MUTE_REQUEST: 'MANAGE_ORGANIZATION_NOTIFICATION_MUTE_REQUEST',
  MANAGE_NOTIFICATION_MUTE_SUCCESS: 'MANAGE_ORGANIZATION_NOTIFICATION_MUTE_SUCCESS',
  MANAGE_NOTIFICATION_MUTE_FAILED: 'MANAGE_ORGANIZATION_NOTIFICATION_MUTE_FAILED',

  // Load more events
  LOAD_MORE_EVENTS_REQUEST: 'LOAD_MORE_ORGANIZATION_EVENTS_REQUEST',
  LOAD_MORE_EVENTS_SUCCESS: 'LOAD_MORE_ORGANIZATION_EVENTS_SUCCESS',
  LOAD_MORE_EVENTS_FAILED: 'LOAD_MORE_ORGANIZATION_EVENTS_FAILED',
  UPDATE_EVENTS_LIST: 'UPDATE_ORGANIZATION_EVENTS_LIST',

  // Reset member invitation state
  RESET_MEMBER_INVITATION: 'RESET_INVITATION_ORGANIZATION_MEMBERS',

  // Reset organization
  RESET_STORE: 'RESET_ORGANIZATION_STORE',
};
