export const profileTypes = {

  // Get all discover details
  GET_PROFILE_REQUEST: 'GET_PROFILE_DETAILS_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_DETAILS_SUCCESS',
  GET_PROFILE_FAILED: 'GET_PROFILE_DETAILS_FAILED',

  // Get country data
  GET_COUNTRY_REQUEST: 'GET_COUNTRY_DETAILS_REQUEST',
  GET_COUNTRY_SUCCESS: 'GET_COUNTRY_DETAILS_SUCCESS',
  GET_COUNTRY_FAILED: 'GET_COUNTRY_DETAILS_FAILED',

  // update profile data
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_DETAILS_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_DETAILS_SUCCESS',
  UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_DETAILS_FAILED',

  // update profile data
  UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_DETAILS_REQUEST',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_DETAILS_SUCCESS',
  UPDATE_PASSWORD_FAILED: 'UPDATE_PASSWORD_DETAILS_FAILED',

  // update profile data
  GET_TIMEZONE_REQUEST: 'GET_TIMEZONE_DETAILS_REQUEST',
  GET_TIMEZONE_SUCCESS: 'GET_TIMEZONE_DETAILS_SUCCESS',
  GET_TIMEZONE_FAILED: 'GET_TIMEZONE_DETAILS_FAILED',

  // update phone data
  UPDATE_PHONE_REQUEST: 'UPDATE_PHONE_DETAILS_REQUEST',
  UPDATE_PHONE_SUCCESS: 'UPDATE_PHONE_DETAILS_SUCCESS',
  UPDATE_PHONE_FAILED: 'UPDATE_PHONE_DETAILS_FAILED',
  
  // check phone otp data
  CHECK_PHONE_OTP_REQUEST: 'CHECK_PHONE_OTP_DETAILS_REQUEST',
  CHECK_PHONE_OTP_SUCCESS: 'CHECK_PHONE_OTP_DETAILS_SUCCESS',
  CHECK_PHONE_OTP_FAILED: 'CHECK_PHONE_OTP_DETAILS_FAILED',
  CHECK_PHONE_OTP_UPDATE: 'CHECK_PHONE_OTP_DETAILS_UPDATE',

  // update email data
  UPDATE_EMAIL_REQUEST: 'UPDATE_EMAIL_DETAILS_REQUEST',
  UPDATE_EMAIL_SUCCESS: 'UPDATE_EMAIL_DETAILS_SUCCESS',
  UPDATE_EMAIL_FAILED: 'UPDATE_EMAIL_DETAILS_FAILED',

  // update single profile data
  SINGLE_PROFILE_REQUEST: 'SINGLE_PROFILE_DETAILS_REQUEST',
  SINGLE_PROFILE_SUCCESS: 'SINGLE_PROFILE_DETAILS_SUCCESS',
  SINGLE_PROFILE_FAILED: 'SINGLE_PROFILE_DETAILS_FAILED',

  // get current user time zone
  CURRENT_USER_TIMEZONE_REQUEST: 'CURRENT_USER_TIMEZONE_DETAILS_REQUEST',
  CURRENT_USER_TIMEZONE_SUCCESS: 'CURRENT_USER_TIMEZONE_DETAILS_SUCCESS',
  CURRENT_USER_TIMEZONE_FAILED: 'CURRENT_USER_TIMEZONE_DETAILS_FAILED',
};
